name: Java CI with Maven
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

# https://github.com/marketplace/actions/docker-build-push-action
# docker push wheeler0772/hello-world-001-images:tagname
# Error: Command failed: docker login -u *** --password-stdin docker.io

      # - name: Dump DOCKER_USERNAME
      #   run: echo DOCKER_USERNAME ${{ secrets.DOCKER_USERNAME }}

      # - name: Dump DOCKER_PASSWORD
      #   run: echo DOCKER_PASSWORD ${{ secrets.DOCKER_PASSWORD }}   

      # - name: Build & push Docker image
      #   uses: mr-smithers-excellent/docker-build-push@v6
      #   with:
      #     image: wheeler0772/hello-world-001-images
      #     tags: latest
      #     registry: docker.io
      #     dockerfile: Dockerfile
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

# https://github.com/marketplace/actions/build-and-push-docker-images#git-context

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: wheeler0772/hello-world-001-images:latest